language: python
python:
  - "2.7"
  - "3.3"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then pip install twisted; fi
  - python setup.py develop
script:
  - PYTHONWARNINGS="ignore" nosetests $(if [[ $TRAVIS_PYTHON_VERSION == 3.* ]]; then echo --fresher-tags=~twisted; fi) --with-fresher tests
